config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :boards
  resources :statuses
  resources :notes
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :statuses
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :status
  belongs_to :user
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :board
  has_many :notes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :boards
  has_many :statuses
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all.order(created_at: :desc)
  end
  def create
    Board.create(board_params.merge(user_id: current_user.id))
    redirect_to boards_url
  end
  def new
    @board = Board.new
  end
  def show
    @board = Board.find(params[:id])
  end
  def board_params
    params.require(:board).permit(:title)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @boards = Board.all
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    Note.create(note_params.merge(user_id: current_user.id))
  end
  def delete
    Note.find(params[:id]).destroy(note_params)
  end
  def update
    Note.find(params[:id]).update(note_params)
  end
  def notes_params
    params.require(:note).permit(:status_id, :body)
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  def new
    @status = Status.new
  end
  def create
    Status.create(status_params.merge(board_id: current_user.id))
    redirect_to :root
  end
  def delete
    Status.find(params[:id]).destroy(status_params)
  end
  def update
    Status.find(params[:id]).update(status_params)
  end
  def show
    @status = Status.find(params[:id])
  end
  def status_params
    params.require(:status).permit(:board_id, :name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/new.html.erb
<section>
  <%= form_for @board do |f| %>
    <%= f.text_field :title, placeholder: 'Title' %>
    <br>
    <%= f.submit %>
  <% end %>
</section>

app/views/boards/show.html.erb
<header>
  <% if user_signed_in? %>
    <%= link_to('You are logged in. Logout?', destroy_user_session_path, method: :delete) %>
  <% else %>
    <%= link_to('Login', new_user_session_path)  %>
  <% end %>
</header>

<section>
  <h1><%= @board.title %></h1>
  <p>Statuses: </p>
  <% @board.statuses.each do |status|%>
    <div>
      <h2><%= link_to status.name, status_url(status)%></h2>
    </div>
  <% end %>
  <% if user_signed_in? %>
    <div>
      <p><%= link_to 'New status', new_status_path(@status)  %> | <%= link_to 'Go back', :back %></p>
    </div>
  <% else %>
    <p>You must be signed in to create a status | <%= link_to 'Go back', :back %></p>
  <% end %>

</section>

app/views/home/index.html.erb
<header>
  <% if user_signed_in? %>
    <%= link_to('You are logged in. Logout?', destroy_user_session_path, method: :delete) %>
  <% else %>
    <%= link_to('Login', new_user_session_path)  %>
  <% end %>
</header>
<section>
  <h1>Welcome</h1>
  <article>
    <% if user_signed_in? %>
    <div>
      <p><%= link_to 'Create new board', new_board_path %></p>
    </div>
    <% else %>
      <p>You must be signed in to create a board.</p>
    <% end %>
    <h1>Boards</h1>
    <% @boards.each do |board|%>
      <div>
        <h2><%= link_to board.title, board_url(board)%></h2>
      </div>
    <% end %>
  </article>


</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoticeBoard</title>
    <%= csrf_meta_tags %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statuses/new.html.erb
<section>
  <%= form_for @status do |f| %>
    <%= f.text_field :name, placeholder: 'Add a status' %>
    <br>
    <%= f.submit %>
  <% end %>
</section>

app/views/statuses/show.html.erb
<section>
  <h1><%= @status.name %></h1>
</section>